### ISSUE TITLE
How do I remove excess indentation

### ISSUE THREAD

**Issue by weir12** [prompt-toolkit/ptpython#424]
Hi:
When I copy a block of code from another editor, it is often accompanied by redundant tabs (such as code from the body of a function)
e.g
```
>>> ^Iresult={}
... ^Ifor cond in all_files.keys():
... ^I^Iresult[cond]={}

IndentationError: unexpected indent

unexpected indent (<stdin>, line 1)
```
The IPython environment will automatically remove excess indentation.
I believe PTPython also has this feature, but I don't know how to activate it.
thanks!

**Comment by jonathanslenders** [comment]
Hi @weir12,

There are two things here.

1. It looks like the code you were copying was indented using tabs instead of spaces. We don't display this correctly. We could turn tabs into spaces when pasting, or simply render correctly with the right tabstops.

2. We can indeed unindent blocks as a whole. I take this as a feature request.

**Comment by weir12** [comment]
Hi @jonathanslenders,
Thank you for your timely help.
So how should I deal with this awkward situation,except for removing excess indentation manually.

**Comment by jonathanslenders** [comment]
Fixed here: https://github.com/prompt-toolkit/ptpython/pull/428

**Comment by weir12** [comment]
Thank you!
